### PR TITLE
Heroku Required changes: (1)Package.JSON (2)Profile (3)README.me  (4)…

### PR DESCRIPTION
**Pull request by LfifteenA**
…server.js file (5)Images removed

(1) Package.JSON file updated - changed scripts from “dev: nodemon app.js" to "start" : "node server.js" for Heroic deployment
(2) Profile file created - Heroku required to communicate (to Heroku) how to start the server (via web) and what language to run on it (node server.js)
(3) README.me file updated - To ensure alignment with “Description” updates in the Package.JSON file (see #1)
(4) server.js file created - Heroku required to communicate (to Heroku)  how to run the app (use express, declares ports, sets up routes and file paths for static code, etc)
(5) Images removed - Deleted unnecessary icon images from folder

### CODE REVIEW

**Comment by LfifteenA** [comment]
@tinuola @carolinambravo @Cindywangtelanoff I am going to merge this request just so I can deploy Heroku on my next commit / push. Feel free to review / suggest changes even if the pull request is closed. And feel free to revert this merge later (or whatever you need to do) if it causes a coding conflict down the line.

**Comment by wykhuh** [comment]
@LfifteenA What is the "Heroku Update" folder for? You should be editing the existing files, not creating copies.

**Comment by LfifteenA** [comment]
I successfully cloned an edited my files on my computer but no matter what I try they could not push or merge them into the GitHub. I wasted over an hour trying to do it and was running out of time so I got creative. 

I think changing my username and password for Git Hub may have messed up my Git configurations.

I plan to ask you on tomorrow (so you can see my screen) if it is just an user error or a combination of user and configuration error. 

Also, I changed the name of the folder because I didn't want to confuse this offline upload with the clones I am making to my "remote Git repo."  GitHub seems to still recognize the changes so hopefully this is an acceptable work-around?

**Comment by LfifteenA** [comment]
Sorry for the typos I'm using my phone. I think changing my username and password for get Hub may have messed up my configurations. I was going to ask you on Saturday if it was user error or a combination of user and configuration error

**Pull request closed without merging**
